# Aula 3 - aprendendo numpy

In [94]:
import numpy as np
import statistics
import math as mt

In [2]:
#gerando um array números aleatórios

data = np.random.randn(2,3)

In [4]:
#selecionando o tipo de dados
type(data)

numpy.ndarray

In [7]:
#pegando o desvio padrão
data.std()

0.9108187688266305

In [6]:
#aumentando cada elemento por 10
data * 10

array([[-7.94618923, 17.30819189,  0.79139408],
       [-2.61171219, 14.29166172, -0.36777432]])

In [9]:
#somando cada elemento da matriz 
data + data

array([[-1.58923785,  3.46163838,  0.15827882],
       [-0.52234244,  2.85833234, -0.07355486]])

In [11]:
#pesquisando o numero de linhas e colunas, shapes
data.shape

(2, 3)

In [12]:
#Mostra todos os tipos de dados de cada elemento
data.dtype

dtype('float64')

In [13]:
#data  é igual a uma lista com diversos tipos de elementos
#criando uma lista e transformando para um array 

data1 = [6, 7.5, 8, 0, 1]

In [15]:
#data1 é uma lista e aparecera as propriedades de lista
type(data1)

list

In [16]:
#transformar em array a lista
arr1 = np.array(data1)

In [18]:
#adicianando data a uma nova variavel e transformando em array
type(arr1)

numpy.ndarray

In [19]:
#criando uma nova lista dentro de outra lista
data2 = [[1, 2, 3], [4, 5, 6]]

In [20]:
type(data2)

list

In [23]:
#localizando um elemento na lista, no qual primeiro é a linha e segundo é a coluna 
data2[0] [0]

1

In [25]:
#convertendo a lista em array
arr2 = np.array(data2)
arr2 

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
#localizando elemento no array
#    L, C  
arr2[1, 2] 

6

In [31]:
#fazendo o shape
arr2.shape


(2, 3)

In [32]:
#descobrindo o tipo de dados
arr2.dtype

dtype('int32')

In [33]:
#pegando os numeros de dimensões
arr2.ndim

2

In [35]:
#criando matriz de 0
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
#fazendo uma matriz de mais linhas
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
#precisando de ajuda na função
?print('oi')

Object `print('oi')` not found.


In [40]:
?np.zeros

In [44]:
#cria uma matriz vazia
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [43]:
#criando vetores com numpy
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
#criando matriz de identidade
np.eye(10, 10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [46]:
#Criando uma matriz de transferencia
np.ones((10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [47]:
#criando um array do tipo float
arr3 = np.array([1, 2, 3], dtype = np.float64)
arr3

array([1., 2., 3.])

In [49]:
#criando um array do tipo int
arr4 = np.array([1, 2, 3], dtype = np.int64)
arr4

array([1, 2, 3], dtype=int64)

O que é um array?
Para que serve um array?

In [50]:
#declarando um array
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [51]:
#somando um array
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [52]:
#Subtraindo um array
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [53]:
#dividindo o array
1/ arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [54]:
#elevando
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [55]:
#comparar os elementos de um array 
arr > 2

array([[False, False,  True],
       [ True,  True,  True]])

In [56]:
#convertendo de true para o que pedi
arr [arr > 2]

array([3, 4, 5, 6])

In [57]:
#contando numero de elemento
len(arr[arr > 2])

4

In [58]:
#somando os elementos do array e fazendo a media
arr.sum()/len(arr)

10.5

In [87]:
#criando uma função para tirar a media
def media(array):
    media = np.array(array)
    return media.sum()/media.size

In [88]:
media([1, 2, 3, 4, 5, 6])

3.5

In [89]:
#contando os elementos do array 
arr.size

6

In [ ]:
#Calculando percentil
def percentiles(x):
    
    

In [133]:
#calculando a mediana
def mediana(x):
    arr = np.array(x) #Transforma lista em array
    arr.sort() #Reordenar o vetor
    if (arr.size % 2 == 0):#Localizar a posição da mediana
        A = (int(arr.size / 2)-1)
        B = int(arr.size/2)
        C = arr[A]
        D = arr[B]
        E = (C + D) / 2
        return (E)
    else:
        A = mt.ceil(arr.size/2)
        return (arr[A])

In [138]:
mediana([1, 2, 3, 4, 5, 6])

3.5

In [140]:
arr4 = np.random.randn(876000)
arr4.size

876000

In [141]:
arr4[0:3]

array([ 0.91718601,  0.01270432, -0.02837194])

In [142]:
arr4.sum()

332.0416033816066

In [143]:
arr4.mean()

0.00037904292623471074

In [144]:
arr4.min()

-4.798173966438768

In [145]:
arr4.max()

5.141115670089014

In [156]:
arr4[:1000]

array([ 9.17186012e-01,  1.27043208e-02, -2.83719365e-02, -6.24589366e-01,
       -3.04860776e-01,  4.66267540e-01,  5.93530293e-01, -3.33272211e-01,
       -4.31143854e-01,  2.95775100e-01, -5.40855839e-01, -3.65329884e+00,
       -3.47614460e-01, -1.72388595e+00,  2.67549483e-01,  1.20519709e-01,
        1.00329969e+00,  1.64978027e+00, -1.09275194e-01,  4.62504835e-01,
       -1.12794871e+00,  2.36193093e+00,  1.13295323e+00,  4.12189550e+00,
       -7.66232055e-01,  2.05440452e-01,  9.64571336e-01,  2.40662335e-02,
        1.15150800e+00,  4.65017603e-01,  1.40543404e+00,  2.17626897e-01,
       -7.17256448e-02, -1.31263952e+00,  4.93779471e-01,  7.48284635e-01,
        1.37152310e+00,  8.26337697e-01, -3.06090732e+00, -1.09802912e+00,
       -1.93206495e-01,  8.19436025e-01, -1.10379136e-01,  1.97014007e+00,
        2.01152780e-01,  4.57228906e-01,  1.45174270e+00, -5.07064608e-01,
       -4.36960568e-01,  7.91881605e-01,  1.26164083e-01, -7.87089667e-01,
        1.87157538e-01,  

In [158]:
#fazendo um array 2d
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [159]:
#pegar a posição
arr2d[0][0]

1

In [160]:
arr2d[0,0]

1

In [165]:
arr5 = np.empty((3,3,3))
arr5

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
        [2.11394409e-307, 1.42419938e-306, 7.56603881e-307],
        [8.45603440e-307, 2.11397635e-307, 1.11261570e-306]],

       [[1.29062229e-306, 7.56599807e-307, 8.90104239e-307],
        [1.24610383e-306, 1.69118108e-306, 8.06632139e-308],
        [1.20160711e-306, 1.69119330e-306, 1.33511562e-306]],

       [[8.01089061e-307, 1.78020576e-306, 8.06638080e-308],
        [8.01106038e-307, 6.89805151e-307, 1.78020169e-306],
        [1.42410974e-306, 1.42404727e-306, 1.24985552e-311]]])

In [168]:
arr5[0, 1, 2]

7.566038813812667e-307

In [174]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob','Will','Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [175]:
data = np.random.randn(7,4)
data

array([[-1.34811156, -0.18936276, -1.86096301, -0.42843242],
       [-2.11947937, -1.26885451, -0.51154541, -0.4049687 ],
       [ 0.27183863,  0.73759342,  1.77088111, -0.77802748],
       [-1.66130877, -0.09738484, -0.58991   , -0.4630513 ],
       [ 0.93547602, -1.06975738,  1.20997568,  0.83330655],
       [-0.1450475 , -0.1516621 ,  0.8875579 , -0.81852042],
       [ 0.20141874, -2.18717068, -1.0366844 , -1.21403123]])

In [176]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [177]:
#Retorna os valores relacionado ao bob
data [names == 'Bob']

array([[-1.34811156, -0.18936276, -1.86096301, -0.42843242],
       [-1.66130877, -0.09738484, -0.58991   , -0.4630513 ]])

In [178]:
cond = names == 'Bob'

In [180]:
#Tudo que não for 'cond' ele traz
data[~cond]

array([[-2.11947937, -1.26885451, -0.51154541, -0.4049687 ],
       [ 0.27183863,  0.73759342,  1.77088111, -0.77802748],
       [ 0.93547602, -1.06975738,  1.20997568,  0.83330655],
       [-0.1450475 , -0.1516621 ,  0.8875579 , -0.81852042],
       [ 0.20141874, -2.18717068, -1.0366844 , -1.21403123]])

In [182]:
#Trazendo mais 
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [184]:
#Trazendo os resultados
data[mask]

array([[-1.34811156, -0.18936276, -1.86096301, -0.42843242],
       [ 0.27183863,  0.73759342,  1.77088111, -0.77802748],
       [-1.66130877, -0.09738484, -0.58991   , -0.4630513 ],
       [ 0.93547602, -1.06975738,  1.20997568,  0.83330655]])

In [185]:
#Trazendo o que não é will e bob
data[~mask]

array([[-2.11947937, -1.26885451, -0.51154541, -0.4049687 ],
       [-0.1450475 , -0.1516621 ,  0.8875579 , -0.81852042],
       [ 0.20141874, -2.18717068, -1.0366844 , -1.21403123]])

In [202]:
#Recorta os dados 
data.reshape(28, 1 )

array([[-1.34811156],
       [-0.18936276],
       [-1.86096301],
       [-0.42843242],
       [-2.11947937],
       [-1.26885451],
       [-0.51154541],
       [-0.4049687 ],
       [ 0.27183863],
       [ 0.73759342],
       [ 1.77088111],
       [-0.77802748],
       [-1.66130877],
       [-0.09738484],
       [-0.58991   ],
       [-0.4630513 ],
       [ 0.93547602],
       [-1.06975738],
       [ 1.20997568],
       [ 0.83330655],
       [-0.1450475 ],
       [-0.1516621 ],
       [ 0.8875579 ],
       [-0.81852042],
       [ 0.20141874],
       [-2.18717068],
       [-1.0366844 ],
       [-1.21403123]])

In [204]:
data.T

array([[-1.34811156, -2.11947937,  0.27183863, -1.66130877,  0.93547602,
        -0.1450475 ,  0.20141874],
       [-0.18936276, -1.26885451,  0.73759342, -0.09738484, -1.06975738,
        -0.1516621 , -2.18717068],
       [-1.86096301, -0.51154541,  1.77088111, -0.58991   ,  1.20997568,
         0.8875579 , -1.0366844 ],
       [-0.42843242, -0.4049687 , -0.77802748, -0.4630513 ,  0.83330655,
        -0.81852042, -1.21403123]])

In [207]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [208]:
arr1

array([1, 2, 3])

In [212]:
#Unir dois arrays
np.concatenate((arr1, arr2), axis = 0)

array([1, 2, 3, 4, 5, 6])

In [213]:
#Agrupar valores iguais
np.unique([1, 1, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5 ])

array([1, 2, 3, 4, 5])